language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
after_script: NODE_ENV=test YOURPACKAGE_COVERAGE=1 mocha test --require blanket --reporter mocha-lcov-reporter --recursive | ./node_modules/coveralls/bin/coveralls.js
